additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: #Update it with your base domain 
# Instead of NAT Gateway if you want to use Proxy for internet connection then update the Proxy details below and uncomment the parameters
# proxy:
#   httpProxy: http://<username>:<pswd>@<ip>:<port> 
#   httpsProxy: https://<username>:<pswd>@<ip>:<port> 
#   noProxy: ec2.<aws_region>.amazonaws.com,elasticloadbalancing.<aws_region>.amazonaws.com,s3.<aws_region>.amazonaws.com 
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: demo #provide your cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16  #Update it with your vpc cidrblock
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-west-2 #Update with AWS region where you want to deploy openshift cluster
publish: Internal 
# Update Red Hat Pull secret below
pullSecret: '<ADD your Red Hat Pull Secret HERE>'
# update your SSH key below
sshKey: | <ADD SSH KEY HERE>
  
